secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_username:
    file: ./secrets/db_username.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt

services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_password
      MYSQL_DATABASE: course_registration
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    secrets:
      - db_password
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    networks:
      - internal

  backend:
    build: ./courseregistration
    depends_on:
      - db
    secrets:
      - db_password
      - db_username
      - jwt_secret
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/course_registration
    networks:
      - internal

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
      - adminer
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge